name: build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md"]

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 17
  VERSION: mc1.20.1-0.1.1-beta-fabric
  VERSION_TYPE: beta
  RELEASE_NAME: 0.1.1 (beta) for Fabric 1.20.1
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout The Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Setup Gradle for optimal use
        uses: gradle/actions/setup-gradle@v4

      - name: Generate and submit dependency graph for GiHub vulnerabilities scanner
        uses: gradle/actions/dependency-submission@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

        # Only publish on push to main branch
      - name: Publish Build Artifacts to GitHub Release and Modrinth
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          github-tag: "v${{env.VERSION}}"
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: "${{env.VERSION_TYPE}}"
